In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:

from pathlib import Path

# Kiểm tra thư mục hiện tại
print("Current directory:", Path.cwd())

# Liệt kê các file trong thư mục data
data_dir = Path("data")
for file in data_dir.rglob("*"):
    if file.is_file():
        print(file)

Current directory: /home/deeplearning/projects/ml/ml-zoomcamp/homework-1
data/car_fuel_efficiency_2026.csv

In [5]:
import pandas as pd

df = pd.read_csv("data/car_fuel_efficiency_2026.csv")

# Xem 5 dòng đầu tiên
display(df.head())

# Xem kích thước dữ liệu
print(df.shape)

# Xem tên các cột
print(df.columns.tolist())

# Xem kiểu dữ liệu
print(df.dtypes)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

(10000, 11)
['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors', 'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'fuel_efficiency_mpg']
model_year               int64
origin                  object
fuel_type               object
drivetrain              object
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [6]:
len(df)

10000

In [7]:
df["fuel_type"].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [8]:
df["fuel_type"].nunique()

3

In [9]:
df.isna().sum().sum()

np.int64(1141)

In [10]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [14]:
print(df.columns.tolist())

['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors', 'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'fuel_efficiency_mpg']

In [15]:
display(df.head())

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [17]:
# 1. Kiểm tra kích thước dữ liệu
print("Shape:", df.shape)

# 2. Kiểm tra tên tất cả các cột
print("\nColumns:")
print(df.columns.tolist())

# 3. Xem 5 dòng đầu tiên
print("\nFirst 5 rows:")
display(df.head())

# 4. Kiểm tra kiểu dữ liệu
print("\nData types:")
print(df.dtypes)

Shape: (10000, 11)

Columns:
['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors', 'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'fuel_efficiency_mpg']

First 5 rows:

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Data types:
model_year               int64
origin                  object
fuel_type               object
drivetrain              object
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [18]:
# Tìm giá trị fuel efficiency lớn nhất
df["fuel_efficiency_mpg"].max()

41.2

In [19]:
median_before = df["horsepower"].median()

print("Median before:", median_before)

Median before: 254.0

In [20]:
df["horsepower"] = df["horsepower"].fillna(
    median_before
)

In [21]:
median_after = df["horsepower"].median()

print("Median after:", median_after)

Median after: 254.0

In [22]:
if median_after > median_before:
    print("Yes, it increased")
elif median_after < median_before:
    print("Yes, it decreased")
else:
    print("No")

No

In [23]:
total_weight = df["vehicle_weight"].sum()

print("Total weight:", total_weight)

Total weight: 42867540

In [24]:
print("Total weight (million):", total_weight / 1_000_000)

Total weight (million): 42.86754

In [25]:
weight_thousands = df["vehicle_weight"] / 1000

print(weight_thousands.sum())

42867.54

In [26]:
# Thống kê cột trọng lượng
df["vehicle_weight"].describe()

# Kiểm tra số lượng giá trị thiếu
df["vehicle_weight"].isna().sum()

# Tổng và trung bình
print("Sum:", df["vehicle_weight"].sum())
print("Mean:", df["vehicle_weight"].mean())

Sum: 42867540
Mean: 4286.754